### PR TITLE
RTE Tinymce6

### PR DESCRIPTION
**Pull request by manu37**
As tinyMCE5 has already reached EOL we should consider replace it & integrate tinymce6.

### CODE REVIEW

**Comment by olape-git** [comment]
no Preview in full and full-open, no FA, defaultconfig is with cdn
`$plugin_cf['tinymce6']['CDN']="false";` --> `$plugin_cf['tinymce6']['CDN']="";` must be empty.

**Comment by olape-git** [comment]
no dropdown for heading, p, div, ... in full and full-open

**Comment by lck-git** [comment]
PHP-Version 8.3.11
Debug-Mode notifies

> XH-DEPRECATED: Function XH_encodeJson() is deprecated
> D:\xampp\htdocs\xh180_tests\xh18_testversion\plugins\tinymce6\links.php:89

**Comment by lck-git** [comment]
> no dropdown for heading, p, div, ... in full and full-open

In the inits files, **styleselect** must be replaced by **styles**. This has been renamed in TinyMCE 6.

The separators (vertical bars, pipes, divider) in the toolbar are also no longer output. They only create a space between the buttons.
An alternative would be to use the skin from TinyMCE 5 or to adapt the CSS. 

The language files in langs are also missing. 

Update to the latest version of TinyMCE 6.

**Comment by olape-git** [comment]
> PHP-Version 8.3.11 Debug-Mode notifies
> 
> > XH-DEPRECATED: Function XH_encodeJson() is deprecated
> > D:\xampp\htdocs\xh180_tests\xh18_testversion\plugins\tinymce6\links.php:89

See https://github.com/cmsimple-xh/cmsimple-xh/issues/604

Is the same as under version 5
https://github.com/cmsimple-xh/cmsimple-xh/pull/605/commits/f3338bfbc5b4f30a85a02faf7d7ccdac9342aecb#diff-66fe43d5511317d2dc76cd8fae75e81f50171a30b85cc50fa25a270c335e8d36

**Comment by lck-git** [comment]
Fa_XH must also be extended by [fa/editors/tinymce6/fontawesome](https://github.com/cmsimple-xh/cmsimple-xh/tree/tinymce6/plugins/fa/editors).

**Comment by olape-git** [comment]
> Fa_XH must also be extended by [fa/editors/tinymce6/fontawesome](https://github.com/cmsimple-xh/cmsimple-xh/tree/tinymce6/plugins/fa/editors).

That could be difficult, then we would also have to make a fork of FA. At least as long as Christoph is no longer involved.

**Comment by olape-git** [comment]
OK, I have updated for tests to revision 8.4 and compared the languages with those contained in the config.php of XH.
So far it works quite well.
Why do the languages in TinyMCE5 actually differ from the config.php from XH?

I simply copied Font Awesome under FA from 5 and renamed it to 6, which also works.

That leaves the plugins, there are 30 in version 6 and 46 in version 5 for XH. However, simply copying them does not seem to be sufficient here. That may not make sense either, there are probably newer versions. But xhplugincall i.e. doesn't work either. However, I did not pursue this any further.

**Comment by lck-git** [comment]
> But xhplugincall i.e. doesn't work either. However, I did not pursue this any further.

Anscheinend muss die Zeile auskommentiert werden, dann funktioniert xhplugincall.
https://github.com/cmsimple-xh/cmsimple-xh/blob/99294b02c1f391ee402dcfa769575cfd0f495fc0/plugins/tinymce6/tinymce/plugins/xhplugincall/plugin.min.js#L8

**Comment by manu37** [comment]
> > no dropdown for heading, p, div, ... in full and full-open
> 
> In the inits files, **styleselect** must be replaced by **styles**. This has been [renamed in TinyMCE 6](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#things-we-renamed).
> 
> The separators (vertical bars, pipes, divider) in the toolbar are also no longer output. They only create a space between the buttons. An alternative would be to use the skin from TinyMCE 5 or to adapt the CSS.
> 
> The language files in [langs](https://github.com/cmsimple-xh/cmsimple-xh/tree/tinymce6/plugins/tinymce6/tinymce/langs) are also missing.
> 
> Update to the latest version of [TinyMCE 6](https://www.tiny.cloud/docs/tinymce/6/changelog/?utm_campaign=editor_referral&utm_medium=help_dialog&utm_source=tinymce).

Since there are no skins in the free version, I remove the pipes in the init_dropdown files.

**Comment by manu37** [comment]
solved with #626

**Pull request closed without merging**
