### PR TITLE
TinyMCE5 base 1.7

### PR DESCRIPTION
**Pull request by manu37**
see #491 
but based on 1.7 (TinyMCE5 optional, default editor still TinyMCE4)
Please ignore #491 as TinyMCE5 will be merged into master over 1.7.

### CODE REVIEW

**Comment by manu37** [comment]
see #497

**Comment by cmb69** [comment]
> see #497

Hm, this is #497. Has this been closed inadvertently?

**Comment by manu37** [comment]
Ups, closed the wrong one. Hopefully this is the right one.

**Comment by cmb69** [comment]
@manu, I have squashed and applied this to 1.7+, except for the last commit (5de02a705d25acc71a61bcdee34744740d62ae8e) which should go into https://github.com/cmb69/fa_xh, so that it doesn't get overwritten for the next update. I don't understand why this is needed, though. Can you please clarify?

**Comment by manu37** [comment]
> @manu, I have squashed and applied this to 1.7+, except for the last commit ([5de02a7](https://github.com/cmsimple-xh/cmsimple-xh/commit/5de02a705d25acc71a61bcdee34744740d62ae8e)) which should go into https://github.com/cmb69/fa_xh, so that it doesn't get overwritten for the next update. I don't understand why this is needed, though. Can you please clarify?

"Since Tinymce5 is not capable (yet) to handle multiple nonEditable cl…
…asses, lets add the mceNonEditable class in editors/tinymce5/fontawesome/plugin.min.js." I wrote it in commit's Title/remarks.

**Pull request closed without merging**
