### PR TITLE
Tinymce5

### PR DESCRIPTION
**Pull request by manu37**
Here comes the new TinyMCE5 RTE, as TinyMCE4 has reached EOL at the end of past year.
Main new features:
- new drop down menu (the full icon menu is ugly. Small icons menu is only available in premium plugins)
- image upload ability by enhanced image plugin or just drag & drop into editor area
- edit image ability
- refactored admin section
For comparison I left the TinyMCE4 remaining, but the goal is to get rid of.

### CODE REVIEW

**Comment by cmb69** [comment]
What about *adding* TinyMCE5 to XH 1.7.5, but keeping TinyMCE4 as default editor in that version?

**Comment by manu37** [comment]
> 
> 
> What about _adding_ TinyMCE5 to XH 1.7.5, but keeping TinyMCE4 as default editor in that version?

Good idea!
How to do? Create a PR from the TinyMCE5 Branch into 1.7? And reset Tiny4 as default?

**Comment by cmb69** [comment]
> Create a PR from the TinyMCE5 Branch into 1.7? And reset Tiny4 as default?

Yes, that may be the best option.

**Comment by manu37** [comment]
See #497

**Comment by cmb69** [comment]
If we keep TinyMCE 4 for XH 1.7.5, we should update to the latest 4.9.11. @manu37, could you please do that?

**Comment by manu37** [comment]
Already done #454.

**Comment by cmb69** [comment]
Thanks!

**Pull request closed without merging**
